# This file contains the hardware device definitions, i.e. what all sensors/switches/lights attached to a hardware
# device.

my_home:
  general:
    - electricity_status
    - hub_battery
    - hub_battery_state

dev_mpr_relay6:
  status:  #entity
  #debug:  #entity
  sensor:  #entity
    - wifi_signal
    - uptime
    - ip_address
    - mac_address
  binary_sensor:
    - touch_key_0
    - touch_key_1
    - touch_key_2
    - touch_key_3
    - touch_key_4
    - touch_key_5
    - touch_key_6
    - touch_key_7
    - touch_key_8
    - touch_key_9
    - touch_key_10
    - touch_key_11
  switch:
    - restart
    - relay_0
    - relay_1
    - relay_2
    - relay_3
    - relay_4
    - relay_5
    - relay_6
  light:
    - id: switch_lights
      effects:
        - None
        - Rainbow
        - CO Alarm
        - Intrusion Alarm

dev_relay8:
  status:  #entity
  sensor:  #entity
    - wifi_signal
    - uptime
    - ip_address
    - mac_address
  switch:
    - restart
    - relay_0
    - relay_1
    - relay_2
    - relay_3
    - relay_4
    - relay_5
    - relay_6
    - relay_7

dev_relay1:
  status:
  #debug:
  sensor:
    - wifi_signal
    - uptime
    - ip_address
    - mac_address
  switch:
    - restart
    - relay_0

dev_mpr_pir_relay:
  status:  #entity
  #debug:  #entity
  sensor:  #entity
    - wifi_signal
    - uptime
    - ip_address
    - mac_address
  binary_sensor:
    - pir_sensor
    - touch_key_0
    - touch_key_1
    - touch_key_2
    - touch_key_3
    - touch_key_4
    - touch_key_5
    - touch_key_6
    - touch_key_7
    - touch_key_8
    - touch_key_9
    - touch_key_10
    - touch_key_11
  switch:
    - restart
    - relay_0
    - relay_1
    - relay_2
    - relay_3
    - relay_4
    - relay_5
    - relay_6
  light:
    - id: switch_lights
      effects:
        - None
        - Rainbow
        - CO Alarm
        - Intrusion Alarm

quin_led_duo_v2_6:
  status:  #entity
  #debug:  #entity
  sensor:  #entity
    - wifi_signal
    - uptime
    - ip_address
    - mac_address
  switch:
    - restart
  light:
    - id: light_1
    - id: light_2

dev_cust1_staircase:
  status:  #entity
  #debug:  #entity
  sensor:  #entity
    - wifi_signal
    - uptime
    - ip_address
    - mac_address
  binary_sensor:
    - grid_power
  switch:
    - restart
    - relay_0

wled_all:
  items:
    - id: masterControls
      sitem_type: Switch
      label: Light
    - id: masterControls
      sitem_type: Slider
      label: Brightness
    - id: masterControls
      item_type: Color
      label: Light Color
      icon: colorwheel

    - id: primaryColor
      item_type: Color
      label: Primary Color
      icon: colorwheel
    - id: secondaryColor
      item_type: Color
      label: Secondary Color
      icon: colorwheel
    - id: fx
      item_type: String
      label: Effect  # fx
      icon: text
    - id: palettes
      item_type: String
      label: Palette
      icon: colorwheel
    - id: presets
      item_type: String
      label: Preset
      icon: text
    - id: speed
      item_type: Dimmer
      label: Effect Speed  # fx speed
      icon: time
    - id: intensity
      item_type: Dimmer
      label: Effect Intensity  # FX Intensity
    - id: presetDuration
      item_type: Dimmer
      label: Preset Duration
      icon: time
    - id: transformTime
      item_type: Dimmer
      label: Preset Transform Time
      icon: time
    - id: presetCycle
      item_type: Switch
      label: Preset Cycle
      icon: time
    - id: sleep
      item_type: Switch
      label: Sleep
      icon: moon
